ALTER TABLE jobs
    ADD COLUMN IF NOT EXISTS gender_preference VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS male_vacancies    INTEGER      NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS female_vacancies  INTEGER      NOT NULL DEFAULT 0;
